# Generated by Django 3.2.8 on 2021-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='customer',
            name='Number_of_Resumes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
